server:
  port: 8001

spring:
  application:
    name: wildlife-park-core
  profiles:
    active: dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: localhost
    # 访问路径可以显示ip地址
    prefer-ip-address: true
