server:
  port: 8001
  servlet:
    context-path: /wp/core

spring:
  application:
    name: wildlife-park-core
  profiles:
    active: dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: localhost
    # 访问路径可以显示ip地址
    prefer-ip-address: true

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  ReadTimeout: 5000
  ConnectTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 10000
        errorThresholdPercentage: 60

feign:
  hystrix:
    enabled: true

logging:
  level:
    com.wildfife.park.core.service.feign.UserAuthFeignService: debug
