server:
  port: 7868
spring:
  application:
    name: wildlife-park-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: wildlife-park-auth # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://wildlife-park-auth
          predicates:
            - Path=/wp/auth/** # 断言，路径相匹配的进行路由
            - Header=X-Request-Id, [a-zA-Z]+\d{6}
            #- After=2017-01-20T17:42:47.789-07:00[America/Denver]
            #- Before=2017-01-20T17:42:47.789-07:00[America/Denver]
            #- Cookie=username,zzyy
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
          # 过滤
          #filters:
          #  - AddRequestHeader=X-Request-red, blue
        - id: wildlife-park-core
            #匹配后提供服务的路由地址
          uri: lb://wildlife-park-core
          predicates:
            - Path=/wp/core/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: localhost
    # 访问路径可以显示ip地址
    prefer-ip-address: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

