CREATE TABLE IF NOT EXISTS `FUNCTIONALITY`
(
    `ID`        BIGINT(20)  NOT NULL AUTO_INCREMENT,
    `NAME`      VARCHAR(80) NOT NULL,
    `MEMO`      TEXT,
    `PARENT_ID` BIGINT(20) DEFAULT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `IDX_UNIQUE_NAME` (`NAME`),
    KEY `IDX_FK_PARENT_ID` (`PARENT_ID`),
    CONSTRAINT `FK_FUNCTIONALITY_FUNCTIONALITY` FOREIGN KEY (`PARENT_ID`) REFERENCES `FUNCTIONALITY` (`ID`)
)