CREATE TABLE IF NOT EXISTS `ROLE_FUNCTIONALITY`
(
    `FUNCTIONALITY_ID` BIGINT(20) NOT NULL,
    `ROLE_ID`          BIGINT(20) NOT NULL,
    PRIMARY KEY (`ROLE_ID`, `FUNCTIONALITY_ID`),
    KEY `IDX_FK_FUNCTIONALITY_ID` (`FUNCTIONALITY_ID`),
    CONSTRAINT `FK_ROLE_FUNCTIONALITY_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`),
    CONSTRAINT `FK_ROLE_FUNCTIONALITY_FUNCTIONALITY` FOREIGN KEY (`FUNCTIONALITY_ID`) REFERENCES `FUNCTIONALITY` (`ID`)
)